# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :adhoc do     #记住这个名字叫adhoc 执行命令的时候要用这个
  gym(
    scheme: "JMTestAutoPackage",
    export_method: "ad-hoc",
    output_directory: "build",
    output_name: "test.ipa"
  )
  end
end
